import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { it } from 'vitest';
import { findFreePortFrom } from '../src/util/ports.js';
import { Gateway } from '../src/gateway/server.js';
import { Store } from '../src/store/db.js';
import { TokenAuthority } from '../src/platform/tokens.js';
import { CredentialBroker } from '../src/autonomy/broker.js';
import { Vault } from '../src/autonomy/vault.js';
import { KarmaxBus } from '../src/contrib/bus.js';
import { ContributionRegistry } from '../src/contrib/registry.js';
import { Overlays } from '../src/store/overlays.js';
import { WorldRegistry } from '../src/world/registry.js';
import { KarmaxApi } from '../src/platform/api.js';
import { seedProfiles } from '../src/agent/profiles.js';
import { McpConnections } from '../src/mcp/connections/store.js';
import assert from 'node:assert/strict';
import { VaultItems } from '../src/autonomy/vault-items.js';
it('unified app search and resource defaults work in the real gateway UI', async () => {
 const priorHome = process.env.KARMAX_HOME;
 const dir=fs.mkdtempSync('/tmp/unified-walkthrough-state-'); process.env.KARMAX_HOME=dir;
 const store=await Store.create(':memory:'); const tokens=new TokenAuthority(), worlds=new WorldRegistry();
 const project=(await store.createProject('Connection demo')); (await seedProfiles(store,'mock'));
 const client={workflow:{getHandle:()=>({query:async()=>[]}),start:async()=>({})}} as any;
 const broker=new CredentialBroker(new Vault(path.join(dir,'vault')));
 const api=new KarmaxApi({store,tokens,worlds,client,broker,taskQueue:'screenshots',contentDir:dir});
 const item=(await new VaultItems(store,broker,undefined,'org_personal').save({type:'login',label:'Demo service login',secrets:{password:'demo-not-a-real-password'}}));
 (await store.setSettings('organization:org_personal','vault',{credentialGrants:[`use-credential:item:${item.id}`]}));
 (await store.createCard({id:'card_demo',provider:'mock',scope:'organization',scopeId:'org_personal',label:'Demo card',cap:10000,available:10000,createdAt:Date.now(),last4:'4242'}));
 (await store.setSettings('organization:org_personal','payments',{cardIds:['card_demo'],budget:2500}));
 const gateway=await Gateway.create({store,tokens,worlds,client,api,broker,bus:new KarmaxBus(),contributions:new ContributionRegistry(),overlays:new Overlays(),taskQueue:'screenshots',staticDir:path.resolve('web'),agentInfo:{provider:'mock',reason:'Isolated screenshot demo'}});
 const running=await gateway.listen(await findFreePortFrom(48765)); const base=running.url;
 const browser=await chromium.launch({headless:true});
 try {
 const context=await browser.newContext({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 const page=await context.newPage(); const errors: string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await context.route('**/api/cards?**',route=>route.fulfill({json:[{id:'card_demo',label:'Demo card',last4:'4242',status:'active',scope:'organization'}]}));
 await context.route('**/api/mcp/registry?**',route=>route.fulfill({json:{servers:[{name:'demo/workspace',title:'Example Workspace (demo)',version:'1.0.0',description:'Demo MCP server',options:[{label:'Remote HTTPS',transport:{type:'http',url:'https://mcp-demo.example/mcp'},fields:[]}]}]}}));
 await context.route('**/api/connections/catalog?**',route=>route.fulfill({json:[{slug:'example',name:'Example app (demo)'}]}));
 const out=process.env.KARMAX_REVIEW_SCREENSHOTS || path.join(dir,'screenshots');fs.mkdirSync(out,{recursive:true});
 async function shot(name: string) {
  await page.evaluate(()=>{let el=(globalThis as any).document.getElementById('review-label');if(!el){el=(globalThis as any).document.createElement('div');el.id='review-label';el.style.cssText='position:fixed;bottom:8px;right:10px;z-index:999999;background:white;color:#333;padding:6px;font:12px system-ui';el.textContent='REVIEW DEMO · isolated data · demo catalog and card';(globalThis as any).document.body.append(el);}});
  await page.screenshot({path:`${out}/${name}.png`});console.log(name);
 }
 await page.goto(base+'/personal/settings#settings-defaults');
 const org=page.locator('[data-resource-defaults="global"]');await org.locator('.resource-vault:not([disabled])').waitFor();
 assert.match(await org.locator('.tf-vault-count').innerText(),/1 selected/);
 await org.scrollIntoViewIfNeeded();await shot('01-organization-defaults');
 await page.goto(base+'/personal/connection-demo/settings#project-defaults');
 const projectBox=page.locator('[data-resource-defaults="project"]');await projectBox.locator('.resource-save:not([disabled])').waitFor();
 assert.match(await projectBox.locator('.tf-vault-count').innerText(),/1 selected/);
 assert.equal(await projectBox.locator('.payment-budget').inputValue(),'25.00');
 await projectBox.locator('.payment-search').fill('Demo');
 await projectBox.locator('.resource-save').click();
 assert.equal((await store.getSettings(project.id,'payments')),undefined);
 assert.equal((await store.getSettings(project.id,'vault')),undefined);
 await projectBox.locator('.payment-budget').fill('10');await projectBox.locator('.resource-save').click();
 await page.waitForFunction(async projectId=>((await (await fetch(`/api/settings/project/${projectId}/payments`)).json()) as any).budget===1000,project.id);
 assert.equal((await store.getSettings(project.id,'payments'))!.cardIds,undefined);

 await projectBox.locator('.resource-vault').click();await page.locator('.vault-grant-all').uncheck();await page.locator('[data-vault-apply]').click();
 await projectBox.locator('[data-remove="card_demo"]').click();await projectBox.locator('.payment-budget').fill('0');
 await projectBox.locator('.resource-save').click();
 await page.waitForFunction(async projectId=>{const r=await fetch(`/api/settings/project/${projectId}/vault`);return ((await r.json()) as any).credentialGrants?.length===0;},project.id);
 assert.deepEqual((await store.getSettings(project.id,'vault'))!.credentialGrants,[]);
 await page.waitForFunction(async projectId=>{const r=await fetch(`/api/settings/project/${projectId}/payments`);return ((await r.json()) as any).budget===0;},project.id);
 assert.deepEqual((await store.getSettings(project.id,'payments'))!.cardIds,[]);
 await projectBox.scrollIntoViewIfNeeded();await shot('02-project-empty-overrides');
 await projectBox.locator('.resource-reset').click();
 await page.waitForFunction(()=>(globalThis as any).document.querySelector('[data-resource-defaults="project"] .tf-vault-count')?.textContent==='1 selected');
 assert.deepEqual((await store.getSettings(project.id,'vault')),{});
 await page.goto(base+'/personal/connection-demo');await page.locator('#expand-task').click();
 await page.locator('#tf-vault-open:not([disabled])').waitFor();assert.equal(await page.locator('#tf-vault-count').innerText(),'1 selected');
 await page.locator('#tf-payments').scrollIntoViewIfNeeded();await shot('03-task-inherits');
 await page.goto(base+'/personal/settings#settings-payments');
 const search=page.locator('#native-connections .mcp-filter');await search.fill('Example');
 await page.locator('#native-connections [data-connector-app]').waitFor();
 await page.locator('#settings-connections').scrollIntoViewIfNeeded();await shot('04-unified-app-search');
 await page.locator('#native-connections [data-connector-app]').click();await page.locator('.connector-signin').waitFor();await shot('05-connector-dialog');
 await page.locator('.connector-close').click();
 assert.deepEqual(errors,[]);
 console.log('PASS: real gateway/browser defaults inheritance, empty overrides, reset, task display and combined search');
 } finally {await browser.close();await running.close();(await store.close());fs.rmSync(dir,{recursive:true,force:true}); if (priorHome === undefined) delete process.env.KARMAX_HOME; else process.env.KARMAX_HOME=priorHome;}
}, 60_000);
