/** Agent-readable map of the first-party HTTP surface used by platform_request. */
export const PLATFORM_API_CATALOG = {
  note: 'Every route is authenticated and capability checked. Colon-prefixed names are path parameters.',
  projects: [
    'GET|POST /api/projects', 'GET|PATCH|DELETE /api/projects/:projectId',
    'GET|POST /api/projects/:projectId/workflow-pins',
    'GET|POST /api/projects/:projectId/objects (data objects: POST {path, mode: seed|readonly|writeback, text|dataBase64} upserts a mount; DELETE ?path=)',
    'GET /api/projects/:projectId/objects/data?path= (download the current version)',
    'GET|POST|DELETE /api/projects/:projectId/services (external → {name, kind: external, connectionSecret}; per-world → {name, kind: per-world, image, containerPort, urlEnv, urlTemplate, seedObject?}; DELETE ?name=)',
    'GET /api/projects/:projectId/services/compose-import (proposals parsed from the repo\'s docker-compose file)',
    'POST /api/tasks/:taskId/objects/promote (body {path}: promote the task world\'s modified copy to the new current version)',
  ],
  tasks: [
    'GET|POST /api/projects/:projectId/tasks', 'GET /api/projects/:projectId/tasks/by-num/:number',
    'GET /api/projects/:projectId/search?q=', 'GET|POST /api/projects/:projectId/tags',
    'PATCH|DELETE /api/tags/:id', 'GET|POST /api/projects/:projectId/views',
    'PATCH|DELETE /api/views/:id', 'POST /api/views/:id/reorder',
    'GET|DELETE /api/tasks/:taskId', 'POST /api/tasks/:taskId/queue',
    'PATCH /api/tasks/:taskId/params|notes|authorization',
    'PUT /api/tasks/:taskId/tags|priority', 'POST /api/tasks/:taskId/tag|archive|signal|target',
    'POST /api/tasks/:taskId/cancel-trigger|run-now|run-again', 'GET /api/tasks/:taskId/runs|widgets',
    'GET /api/tasks/:taskId/checkout', 'POST /api/tasks/:taskId/materialize-local',
    'POST /api/tasks/:taskId/terminal-ticket', 'POST /api/tasks/:taskId/refresh-from-github',
    'POST /api/agent/git/publish', 'POST /api/agent/git/import', 'POST /api/agent/git/refresh-upstream',
  ],
  conversations: [
    'GET /api/tasks/:taskId/agents', 'GET /api/tasks/:taskId/conversation?role=',
    'POST /api/tasks/:taskId/fork-agent', 'GET /api/tasks/:taskId/sessions',
    'GET /api/tasks/:taskId/events?since=', 'POST /api/tasks/:taskId/signal (followUp + role messages an agent)',
  ],
  review: [
    'POST /api/tasks/:taskId/review-action', 'GET /api/tasks/:taskId/review-action/:procId',
    'POST /api/tasks/:taskId/review-action/:procId/stop', 'GET /api/tasks/:taskId/artifact?path=',
    'GET /api/tasks/:taskId/desktop', 'WS /ws/review-action?procId=', 'WS /ws/terminal?taskId=',
  ],
  automation: [
    'GET /api/workflows', 'POST /api/workflows/install', 'POST /api/projects/:projectId/propose-workflow-edit',
    'GET|PUT /api/profiles', 'DELETE /api/profiles/:id',
    'GET /api/models|schema|events/catalog|contributions', 'GET /api/defaults/:projectId/:workflow',
    'GET|PUT /api/settings/global/:workflow', 'GET|PUT /api/settings/project/:projectId/:workflow',
    'GET|PUT /api/settings/quick/global/:workflow', 'GET|PUT /api/settings/quick/project/:projectId/:workflow',
    'POST /api/skills', 'POST /api/safe-mode',
  ],
  credentials: [
    'GET|POST /api/accounts', 'POST /api/accounts/connect', 'PATCH|DELETE /api/accounts/logins/:provider/:account',
    'POST /api/accounts/availability|concurrency|usage/recheck', 'GET /api/accounts/usage',
    'GET /api/credentials?projectId=&taskId=', 'POST /api/credentials/policy?projectId=|taskId=',
    'GET|POST /api/git-profiles', 'GET|PATCH|DELETE /api/git-profiles/:id',
    'GET /api/git-profiles/preflight?projectId=', 'POST /api/git-profiles/default',
    'GET|POST /api/projects/:projectId/secrets (POST {name, value?, file?, mode?} upserts; {env: "<pasted .env>"} bulk-imports; values are write-only)',
    'DELETE /api/projects/:projectId/secrets/:name',
    'POST /api/projects/:projectId/import-copyglobs (classify copyGlobs matches into secrets/objects, then clear copyGlobs)',
  ],
  wiki: [
    'GET /api/organizations/:organizationId/wiki?path= (skill path → page; else table of contents + unconditional entries)',
    'GET|PUT|DELETE /api/organizations/:organizationId/wiki/page?path= (PUT body {path, content, kind: skill|memory, create?, prevPath?})',
    'GET /api/organizations/:organizationId/wiki/search?q=',
    'GET /api/projects/:projectId/wiki?path=', 'GET|PUT|DELETE /api/projects/:projectId/wiki/page?path=',
    'GET /api/projects/:projectId/wiki/search?q=',
  ],
  payments: ['GET /api/payments/providers', 'POST /api/payments/connect', 'GET|POST /api/cards', 'POST /api/cards/:id/fund'],
  administration: [
    'GET|POST /api/users', 'DELETE /api/users/:id',
    'GET|PUT /api/authorization/profiles?projectId=', 'PUT /api/authorization/default',
    'GET|PUT /api/authorization/grants', 'GET /api/audit?since=&limit=',
  ],
  cloud: [
    'GET|PUT /api/projects/:projectId/environment (spec {image, setup[], boot[], includeDocker} + per-provider builds)',
    'GET /api/projects/:projectId/environment/proposal (derived from devcontainer.json, lockfiles, declared services)',
    'POST /api/projects/:projectId/environment/build (bake an immutable artifact for {provider?}; async, status on the build record)',
    'GET|PUT /api/organizations/:organizationId/execution-policy',
    'GET|PUT /api/projects/:projectId/execution-policy',
    'GET /api/organizations/:organizationId/world-providers',
    'PUT|DELETE /api/organizations/:organizationId/world-providers/:provider',
    'POST /api/organizations/:organizationId/world-providers/:provider/test',
    'GET|POST /api/organizations/:organizationId/runner-pools',
    'PATCH|DELETE /api/organizations/:organizationId/runner-pools/:runnerPoolId',
  ],
  operations: [
    'GET /api/activity?projectId=&since=', 'GET /api/dashboard', 'GET /api/diagnostics',
    'GET /api/processes', 'POST /api/processes/kill',
    'GET /api/queue?domain=&projectId=', 'POST /api/queue/prioritize|move?projectId=',
    'POST /api/attachments (JSON dataUrl or image bytes)', 'WS /ws (authorized event stream)',
  ],
} as const;
