/**
 * Agent-readable map of the first-party HTTP surface used by platform_request.
 *
 * This is the ONLY discovery mechanism an agent has for the administrative API,
 * and `tests/gateway-routes.test.ts` walks it to assert every documented route
 * has an explicit capability binding — so an omission here is both undiscoverable
 * *and* untested. When a route is added to `src/gateway/server.ts`, add it here.
 */
export const PLATFORM_API_CATALOG = {
  note: 'Every route is authenticated and capability checked. Identity requirements are independent: human-subject accepts secure task-agent delegation; interactive-human requires a live browser session. Colon-prefixed names are path parameters.',
  identityRequirements: {
    capability: 'Default. No user identity is implied by a capability grant.',
    humanSubject: [
      'POST /api/organizations',
      'POST /api/organizations/:organizationId/repositories/create',
      'GET /api/projects/:projectId/github-merge-eligibility',
      'POST /api/organizations/:organizationId/git-profiles/reuse-user',
    ],
    interactiveHuman: [
      'GET /api/user/export', 'GET|PUT /api/user/default-organization', 'GET|PUT /api/user/onboarding',
      'POST /api/user/account-deletion-request', 'POST /api/invitations/accept',
      'DELETE /api/organizations/:organizationId',
      'POST /api/users', 'DELETE /api/users/:userId',
      'GET|PATCH /api/inbox', 'GET|PUT /api/inbox/preferences',
      'GET|POST|PUT|DELETE /api/user/github-accounts|git-profiles',
      'POST /api/organizations/:organizationId/subscription/checkout|portal|change|cancel|sync-seats (owner only)',
      'POST /api/organizations/:organizationId/github/app-manifest|install-url|authorize',
      'POST /api/organizations/:organizationId/payments/connect',
      'POST /api/vault/items/:itemId/reveal',
      'POST /api/tasks/:taskId/explanations',
      'POST /api/authorization/escalation-targets',
      'POST /api/authorization-requests',
    ],
  },
  resources: ['GET /api/resource-drivers'],
  projects: [
    'GET|POST /api/projects', 'GET|PATCH|DELETE /api/projects/:projectId (PATCH body {name} or {config})',
    // The org-scoped spelling is the ONLY project-create that works on a hosted
    // deployment: bare `POST /api/projects` rejects there with "hosted projects must
    // be created inside an organization". Leaving it undocumented meant an agent on
    // a hosted install had no discoverable way to create a project at all.
    'GET|POST /api/organizations/:organizationId/projects (on hosted, project-create MUST use this form)',
    'POST /api/projects/:projectId/reorder (body {before?: projectId} — sidebar order)',
    'GET|POST /api/projects/:projectId/workflow-pins',
    'GET|POST /api/projects/:projectId/resources', 'GET|PATCH|DELETE /api/projects/:projectId/resources/:resourceId',
    'POST /api/projects/:projectId/resources/:resourceId/import',
    'GET /api/projects/:projectId/resources/scan',
    'POST /api/projects/:projectId/resources/import-copyglobs',
    'POST /api/projects/:projectId/resources/:resourceId/uploads',
    'PUT|POST|DELETE /api/resource-uploads/:uploadId?projectId=',
    'GET|POST /api/projects/:projectId/secrets', 'DELETE /api/projects/:projectId/secrets/:name',
    'GET|POST|DELETE /api/projects/:projectId/services', 'GET /api/projects/:projectId/services/compose-import',
    'GET|PUT /api/projects/:projectId/environment', 'GET /api/projects/:projectId/environment/proposal',
    'POST /api/projects/:projectId/environment/build',
    'GET|POST /api/projects/:projectId/members',
    'DELETE /api/projects/:projectId/members/user|team|organization/:principalId',
  ],
  organizations: [
    'GET|PUT /api/user/default-organization (the signed-in user’s startup workspace)',
    'GET|PUT /api/user/onboarding?organizationId= (hosted-only setup progress + display preference)',
    'GET /api/settings/access?organizationId= (UI-safe write access summary; accepts projectId instead)',
    'GET /api/settings/installation (global operator-only Installation page probe)',
    'GET|POST /api/organizations (POST requires a verified human subject; delegation accepted)',
    'GET|PATCH|DELETE /api/organizations/:organizationId (PATCH body {name}; DELETE body {confirmSlug})',
    'GET /api/organizations/:organizationId/entitlements (current hosted plan, limits, and live usage; private installs are unlimited)',
    'GET /api/organizations/:organizationId/export (full-tenant dump; organization:edit)',
    'GET /api/organizations/:organizationId/usage (spend + token usage for the tenant)',
    'GET|PUT /api/organizations/:organizationId/identity-policy', 'POST /api/organizations/:organizationId/scim-token',
    'GET|POST /api/organizations/:organizationId/members', 'DELETE /api/organizations/:organizationId/members/:userId',
    'GET|POST /api/organizations/:organizationId/invitations',
    'POST /api/invitations/accept (body {token}; interactive human + verified email required)',
    'GET|POST /api/organizations/:organizationId/teams', 'PATCH|DELETE /api/organizations/:organizationId/teams/:teamId',
    'GET|POST /api/organizations/:organizationId/teams/:teamId/members',
    'DELETE /api/organizations/:organizationId/teams/:teamId/members/:userId',
    'GET|PUT /api/organizations/:organizationId/settings/:workflow',
    'GET|PUT /api/organizations/:organizationId/quick-settings/:workflow',
    'GET|PUT /api/organizations/:organizationId/explanation-settings',
  ],
  sourceControl: [
    'GET|PUT /api/projects/:projectId/repository-sources',
    'GET|POST /api/projects/:projectId/repositories',
    'GET /api/projects/:projectId/checkout (portable default-branch checkout instructions)',
    'GET /api/projects/:projectId/github-merge-eligibility (verified human subject; delegation accepted; live external GitHub permission preflight)',
    'DELETE /api/projects/:projectId/repositories/:repositoryId',
    'GET|POST /api/organizations/:organizationId/repositories',
    'POST /api/organizations/:organizationId/repositories/create (verified human subject; delegation accepted only with the authority-pinned GitHub account)',
    'GET /api/organizations/:organizationId/git-connections',
    'GET|PUT /api/organizations/:organizationId/github/app',
    'POST /api/organizations/:organizationId/github/app-manifest|install-url|authorize (interactive human required for OAuth/install redirects); refresh is capability-only',
  ],
  tasks: [
    'GET|POST /api/projects/:projectId/tasks', 'GET /api/projects/:projectId/tasks/by-num/:number',
    'GET /api/projects/:projectId/search?q=', 'GET|POST /api/projects/:projectId/tags',
    'PATCH|DELETE /api/tags/:id', 'GET|POST /api/projects/:projectId/views',
    'PATCH|DELETE /api/views/:id', 'POST /api/views/:id/reorder',
    'GET|DELETE /api/tasks/:taskId', 'POST /api/tasks/:taskId/queue',
    'PATCH /api/tasks/:taskId/params|notes|authorization',
    'PUT /api/tasks/:taskId/tags|priority', 'POST /api/tasks/:taskId/tag|archive|signal|target',
    'POST /api/tasks/:taskId/escalate (body {audience, message}; pauses at the current stage and notifies the selected principals)',
    'POST /api/tasks/:taskId/cancel-trigger|run-now|run-again', 'GET /api/tasks/:taskId/runs|widgets',
    'GET /api/tasks/:taskId/checkout', 'POST /api/tasks/:taskId/materialize-local', 'POST /api/tasks/:taskId/open-command',
    'POST /api/tasks/:taskId/file-checkout',
    'POST /api/tasks/:taskId/terminal-ticket', 'POST /api/tasks/:taskId/refresh-from-github',
    'GET|POST /api/tasks/:taskId/attempts (mutually-exclusive alternates)',
    'PATCH /api/tasks/:taskId/workflow (retarget an unstarted task)',
    'POST /api/tasks/:taskId/stage (move a task to another lifecycle stage)',
    'GET /api/tasks/:taskId/executions', 'GET /api/tasks/:taskId/file?path=',
    'GET|PATCH /api/tasks/:taskId/responsibility (assignee/delegate — task:assign)',
    'GET|POST|DELETE /api/tasks/:taskId/subscribers (task:subscribe)',
    'GET /api/search/fields (the searchable-field registry behind the query grammar)',
    'POST /api/agent/git/publish', 'POST /api/agent/git/import', 'POST /api/agent/git/refresh-upstream',
    'GET /api/agent/github/actions/runs (calling task project; filters repository, branch, event, status, workflow, page)',
    'GET|POST /api/agent/github/actions/runs/:runId (inspect; or rerun-failed/rerun/cancel with github:actions:write)',
    'POST /api/agent/github/actions/dispatch (body {repository?, workflow, ref, inputs?}; github:actions:write)',
    'POST /api/agent/resource-candidates (calling task inferred from its token)',
    'POST /api/agent/escalate (calling task inferred from its token; body {audience, message, urgency?: low|normal|high|critical})',
    'POST /api/agent/permission-requests (body {capabilities, audience, reason, urgency?}; exact task elevation routed to people, teams, or Avatars; high urgency by default)',
    'GET /api/agent/escalation-targets (people, teams, Avatars, and special audience selectors available to the calling task)',
    'GET /api/permission-requests?taskId=&organizationId=',
    'POST /api/permission-requests/:id/resolve?organizationId= (routed human or Avatar: body {action: approve|deny})',
    'POST /api/authorization/escalation-targets (interactive grantor chooser; body {projectId, authorization})',
    'GET|POST /api/authorization-requests (GET by taskId or avatarId; POST routes an over-authorization request)',
    'POST /api/authorization-requests/:id/resolve?organizationId= (routed human or authorizer Avatar: body {action: approve|deny})',
    'POST /api/agent/collaboration/request',
  ],
  conversations: [
    'GET /api/tasks/:taskId/agents', 'GET /api/tasks/:taskId/conversation?role=',
    'POST /api/tasks/:taskId/fork-agent', 'GET /api/tasks/:taskId/sessions',
    'POST /api/conversation-imports?projectId= (raw Codex/Claude JSONL upload)',
    'GET /api/tasks/:taskId/events?since=', 'POST /api/tasks/:taskId/signal (followUp + role messages an agent)',
    'GET|POST /api/tasks/:taskId/explanations (durable annotations; POST body {role, sourceKey, settings?})',
  ],
  review: [
    'POST /api/tasks/:taskId/review-action', 'GET /api/tasks/:taskId/review-action/:procId',
    'POST /api/tasks/:taskId/review-action/:procId/stop', 'GET /api/tasks/:taskId/artifact?path=',
    'GET /api/tasks/:taskId/desktop', 'WS /ws/review-action?procId=', 'WS /ws/terminal?taskId=',
    'GET /api/tasks/:taskId/resources', 'POST /api/tasks/:taskId/resources/:resourceId/promote',
    'POST /api/tasks/:taskId/resources/:resourceId/discard',
    'GET /api/tasks/:taskId/resources/inventory',
    'POST /api/tasks/:taskId/resource-candidates/:candidateId/adopt|discard',
    'GET /api/tasks/:taskId/artifacts', 'POST /api/tasks/:taskId/artifacts/promote',
    'GET /api/artifacts/:artifactId',
    'GET|POST /api/tasks/:taskId/preview-leases', 'DELETE /api/preview-leases/:leaseId',
  ],
  automation: [
    'GET /api/organizations/:organizationId/workflows', 'POST /api/organizations/:organizationId/workflows/install',
    'POST /api/projects/:projectId/propose-workflow-edit',
    'GET|PUT /api/profiles', 'DELETE /api/profiles/:id',
    'GET /api/models|schema|events/catalog|contributions', 'GET /api/defaults/:projectId/:workflow',
    'GET|PUT /api/settings/global/:workflow', 'GET|PUT /api/settings/project/:projectId/:workflow',
    'GET|PUT /api/projects/:projectId/explanation-settings',
    'GET|PUT /api/settings/quick/global/:workflow', 'GET|PUT /api/settings/quick/project/:projectId/:workflow',
    'POST /api/skills', 'POST /api/safe-mode',
  ],
  installation: [
    'GET|PUT /api/settings/paid-launch (installation operator: persisted legal entity, Stripe Billing catalog/secrets, paid-checkout gate, and founder task checklist)',
    'GET|PUT /api/organizations/:organizationId/payments/stripe/platform',
    'GET /api/email', 'POST /api/email/connect|test',
    'GET|POST /api/remote-access',
  ],
  credentials: [
    'GET /api/user/github-accounts', 'POST /api/user/github-accounts/:accountId/active',
    'PUT /api/user/github-accounts/:accountId/identity', 'DELETE /api/user/github-accounts/:accountId',
    'GET|POST /api/user/git-profiles', 'DELETE /api/user/git-profiles/:id',
    'POST /api/user/git-profiles/default', 'POST /api/user/git-profiles/signing-key',
    'GET|POST /api/organizations/:organizationId/accounts',
    'POST /api/organizations/:organizationId/accounts/connect|connect/code',
    'PATCH|DELETE /api/organizations/:organizationId/accounts/keys/:provider/:account',
    'PATCH|DELETE /api/organizations/:organizationId/accounts/logins/:provider/:account',
    'POST /api/organizations/:organizationId/accounts/availability|concurrency|usage/recheck',
    'GET /api/organizations/:organizationId/accounts/usage',
    'GET /api/organizations/:organizationId/credentials?projectId=&taskId=',
    'POST /api/organizations/:organizationId/credentials/policy?projectId=|taskId=',
    'GET|POST /api/organizations/:organizationId/git-profiles',
    'DELETE /api/organizations/:organizationId/git-profiles/:id',
    'GET /api/organizations/:organizationId/git-profiles/preflight?projectId=',
    'POST /api/organizations/:organizationId/git-profiles/default',
    'POST /api/organizations/:organizationId/git-profiles/reuse-user',
    'GET|PUT /api/organizations/:organizationId/github/identity',
    'DELETE /api/organizations/:organizationId/git-connections/:connectionId',
  ],
  vault: [
    'GET|POST /api/vault/items (typed credential items; list/save responses never contain secrets)', 'POST /api/vault/items/:id/reveal (human vault administrator only; audited)', 'DELETE /api/vault/items/:id',
    'POST /api/vault/import/bitwarden (one-time plaintext Bitwarden JSON export; idempotent by Bitwarden item id; encrypted immediately and the request body is not retained as a file)',
    'POST /api/vault/store (agent write-back of a newly created credential; body {id?, type, label, domains?, username?, secrets?})',
    'POST /api/vault/resolve (plaintext reveal, per-item grant + policy gated; body {itemId?|domain?, field?})',
    'POST /api/vault/fill (zero-exposure browser fill via CDP; body {itemId?|domain?, field?, selector, cdpUrl?})',
    'GET /api/vault/requests?taskId=&status=', 'POST /api/vault/requests (escalate for access or report a wrong secret; body {itemId?|domain?, field?, mode?, kind?: access|reset, why, urgency?}; approval is high urgency by default)',
    'POST /api/vault/requests/:id/resolve (human: body {action: once|task|always|deny, itemId?})',
    'GET /api/vault/connectors (hosted 1Password + Git-backed pass; host-local Bitwarden/1Password/pass where available)',
    'POST /api/vault/connectors/:name/connect|config|list|sync|write-back (selective mirror + opt-in write-back; sync body {externalIds, policy?, writeBack?}; list items carry folder for grouping)',
    'POST /api/vault/passkey/enroll|save|login|release (agent-enrolled passkeys via CDP virtual authenticator)',
  ],
  agentMail: [
    'GET /api/organizations/:organizationId/agent-mail?since=&match=&limit= (per-organization agent inbox: address + messages, verification code/link extracted)',
    'GET /api/organizations/:organizationId/agent-mail/providers (mailbox backends + active provider)',
    'POST /api/organizations/:organizationId/agent-mail/connect (connect this organization mailbox; body {provider, domain?|apiKey?})',
    // NOT callable through platform_request — it is in PLATFORM_REQUEST_EXCLUDED_PATHS
    // (it authenticates by minted secret, before the session gate, so it must not be
    // reachable with a task's token). Documented because an operator configures the
    // URL at their mail provider; an agent reads mail via the agent-mail route above.
    'POST /api/agent-mail/ingest?secret= (inbound mail webhook, configured at your mail provider — NOT callable via platform_request; accepts karmax/Postmark/CloudMailin/Mailgun/SendGrid payloads and raw MIME, routed to the recipient organization)',
  ],
  outboundEmail: [
    'GET /api/email (installation-wide outbound sender: active provider, from, configured, provider catalogue)',
    'POST /api/email/connect (connect the sender; body {provider: smtp|resend, from, secret, host?, port?, secure?, user?})',
    'POST /api/email/test (send a test email; body {to?})',
  ],
  wiki: [
    'GET /api/organizations/:organizationId/wiki?path= (skill path → page; else table of contents + unconditional entries)',
    'GET|PUT|DELETE /api/organizations/:organizationId/wiki/page?path= (PUT body {path, content, kind: skill|memory, create?, prevPath?})',
    'GET /api/organizations/:organizationId/wiki/search?q=',
    'GET /api/organizations/:organizationId/wiki/history?path= (append-only database version history)',
    'GET /api/organizations/:organizationId/wiki/suggest?q=',
    'GET /api/projects/:projectId/wiki?path=', 'GET|PUT|DELETE /api/projects/:projectId/wiki/page?path=',
    'GET /api/projects/:projectId/wiki/search?q=', 'GET /api/projects/:projectId/wiki/suggest?q=',
    'GET /api/projects/:projectId/wiki/refs (filterable branch/task views; pass taskId= or branch= to reads)',
  ],
  payments: [
    'GET /api/organizations/:organizationId/subscription/status (hosted SaaS plan and verified seat/payment state; self-hosted reports unmetered)',
    'POST /api/organizations/:organizationId/subscription/checkout|portal|change|cancel|sync-seats (owner-only hosted SaaS billing; mutation calls require Idempotency-Key; checkout body also requires {plan,acceptedPolicies:true,policyVersions})',
    'GET /api/organizations/:organizationId/payments/providers',
    'POST /api/organizations/:organizationId/payments/connect',
    'DELETE /api/organizations/:organizationId/payments/connections/:provider',
    'GET /api/organizations/:organizationId/payments/balance',
    'GET|POST /api/organizations/:organizationId/payments/cardholders',
    'GET /api/organizations/:organizationId/payments/requests',
    'POST /api/organizations/:organizationId/payments/requests/:id/:decision',
    'GET /api/organizations/:organizationId/payments/transactions',
    'GET|POST /api/cards',
    'POST /api/cards/:id/fund',
    'DELETE /api/cards/:id',
  ],
  administration: [
    'GET /api/user/export (human identity only; all data directly linked to the signed-in user)',
    'POST /api/user/account-deletion-request (human identity only; records a verified deletion/offboarding request)',
    'GET|POST /api/users', 'DELETE /api/users/:id',
    'GET|PUT /api/authorization/profiles?projectId=', 'PUT /api/authorization/default',
    'GET|PUT /api/authorization/grants', 'GET /api/audit?since=&limit=',
  ],
  cloud: [
    'GET|PUT /api/organizations/:organizationId/execution-policy',
    'GET|PUT /api/projects/:projectId/execution-policy',
    'GET /api/organizations/:organizationId/world-providers',
    'PUT|DELETE /api/organizations/:organizationId/world-providers/:provider',
    'POST /api/organizations/:organizationId/world-providers/:provider/test',
    'GET|POST /api/organizations/:organizationId/runner-pools',
    'PATCH|DELETE /api/organizations/:organizationId/runner-pools/:runnerPoolId',
  ],
  operations: [
    'GET /api/activity?projectId=&since=', 'GET /api/dashboard', 'GET /api/diagnostics',
    'GET /api/processes', 'POST /api/processes/kill',
    'GET /api/queue?domain=&projectId=', 'POST /api/queue/prioritize|move?projectId=',
    'GET /api/agent-queue (host concurrent-agent-turn queue)', 'POST /api/agent-queue/move (body {turnId, beforeTurnId?})',
    'GET /api/metrics', 'GET|POST /api/remote-access (host-local only; body {action: setup|enable|disable})',
    // The inbox is per-USER by construction, so these three are the human surface:
    // a scoped agent token has no session.userId and gets a 400, whatever its
    // capabilities. An agent watches work through /ws and the task view instead.
    'GET /api/inbox?since= (human identity only — the inbox is per-user)',
    'PATCH /api/inbox/:itemId (human identity only)',
    'GET|PUT /api/inbox/preferences (human identity only)',
    'GET /api/meta (deployment flags: hosted, hostLocal, safeMode — tells you which host-local routes exist here)',
    'POST /api/attachments (JSON dataUrl or image bytes)', 'GET /api/attachments/:attachmentId',
    'POST /api/logout', 'GET /api/health/live', 'GET /api/health/ready',
    'GET /api/platform (this catalog)', 'WS /ws (authorized event stream)',
  ],
} as const;
