const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, 'app.js'), 'utf8');
const start = source.indexOf('function accountErasureMarkup(');
const end = source.indexOf('async function loadAccountErasure(', start);
const context = { esc: value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])) };
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
const preview = { userId: 'user_1', identity: { email: '<script>bad</script>' }, organizations: [], relatedTaskIds: [],
  linkedGit: [], gitProfiles: [], automatic: [], preserved: [], warning: 'not anonymisation', blockers: ['transfer owner'], case: null };
let html = context.accountErasureMarkup(preview);
assert.match(html, /id="erasure-close" disabled/);
assert.ok(!html.includes('<script>bad</script>'));
assert.match(html, /I verified the requester/);
assert.match(html, /Type CLOSE user_1/);
preview.case = { state: 'closed', steps: ['identity'], items: [{ id: 'backups', label: 'Review backups' }] };
html = context.accountErasureMarkup(preview);
assert.ok(!html.includes('id="erasure-close"'));
assert.match(html, /id="erasure-complete" disabled/);
assert.match(html, /manual recovery control, not an automatic restore filter/);
preview.case.items[0].decision = { outcome: 'retained', evidence: '<b>unsafe</b>', reviewAt: Date.now() - 1 };
html = context.accountErasureMarkup(preview);
assert.match(html, /retention review overdue/);
assert.ok(!html.includes('<b>unsafe</b>'));
assert.match(html, /id="erasure-complete" disabled/);
preview.case.items[0].decision.reviewAt = Date.now() + 86400000;
html = context.accountErasureMarkup(preview);
assert.ok(!html.includes('id="erasure-complete" disabled'));
assert.match(html, /Type REVIEWED user_1/);
console.log('Account erasure UI checks passed');
